name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to 
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout fred
      uses: actions/checkout@v2
      with:
        repository: 'freenet/fred'
        fetch-depth: 0
        path: 'fred'

    - name: Download fred
      uses: i3h/download-release-asset@v1.2.0
      with:
        owner: "freenet"
        repo: "fred"
        tag: "latest"
        file: "freenet.jar"

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: updateSetupFile

    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "FreenetInstall_InnoSetup.iss"

      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        path: "Output"
        name: wininstaller-innosetup

