name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to 
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Checkout fred
      uses: actions/checkout@v2
      with:
        repository: 'freenet/fred'
        fetch-depth: 0
        path: 'fred'

    - name: Download fred from the Github Release
      uses: i3h/download-release-asset@v1.2.0
      with:
        owner: "freenet"
        repo: "fred"
        tag: "latest"
        file: "freenet.jar"

    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: updateSetupFile

    - name: Building the installer
      run: |
        "%programfiles(x86)%\Inno Setup 6\iscc.exe" "FreenetInstall_InnoSetup.iss"
      shell: cmd

    - name: Sign the installer
      uses: nextgens/authenticode-sign-action@v1.0.0
      with:
        certificate: '${{ secrets.CERTIFICATES }}'
        credentials: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
        key-uri: "projects/fpi-codesign/locations/europe-west3/keyRings/code-signing/cryptoKeys/certificate/cryptoKeyVersions/1"
        folder: "Output"
        recursive: true

    - name: Verify the signature
      run: call "%programfiles(x86)%/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe" verify /v /pa "Output/FreenetInstaller.exe"
      shell: cmd

    - name: Upload the installer as an artifact
      uses: actions/upload-artifact@v2
      with:
        path: "Output/FreenetInstaller.exe"
        name: wininstaller-innosetup

